import NavBar from "./components/navbar";
import "./globals.css";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className="bg-black font-mono">
                {children}
                <NavBar />
            </body>
        </html>
    );
}
